name: Go
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
      env:
        GO111MODULE: "on"
        GOPROXY: "https://proxy.golang.org"

    - name: Test
      run: go test -race ./...
      env:
        GO111MODULE: "on"
        GOPROXY: "https://proxy.golang.org"
